
import static java.awt.SystemColor.text;
import java.awt.TextArea;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS ROG
 */
public class AplikasiPenghitungKata extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenghitungKata
     */
    public AplikasiPenghitungKata() {
        initComponents();
        inputTextArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                hitung();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                hitung();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                hitung();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kataLabel = new javax.swing.JLabel();
        HitungButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        CariButton = new javax.swing.JButton();
        KeluarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        CariTextField = new javax.swing.JTextField();
        SimpanButton = new javax.swing.JButton();
        KarakterLabel = new javax.swing.JLabel();
        KalimatLabel = new javax.swing.JLabel();
        ParagrafLabel = new javax.swing.JLabel();
        HasilCariLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Masukkan Kalimat");

        jLabel3.setText("Cari Kata :");

        kataLabel.setText("Jumlah Kata :");

        HitungButton.setText("Hitung");
        HitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        CariButton.setText("Cari");
        CariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariButtonActionPerformed(evt);
            }
        });

        KeluarButton.setText("Keluar");
        KeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarButtonActionPerformed(evt);
            }
        });

        inputTextArea.setColumns(20);
        inputTextArea.setRows(5);
        jScrollPane1.setViewportView(inputTextArea);

        SimpanButton.setText("Simpan");
        SimpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanButtonActionPerformed(evt);
            }
        });

        KarakterLabel.setText("Jumlah Karakter :");

        KalimatLabel.setText("Jumlah Kalimat :");

        ParagrafLabel.setText("Jumlah Paragraf :");

        HasilCariLabel.setText("Hasil Pencarian : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(kataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(HitungButton)
                        .addGap(91, 91, 91)
                        .addComponent(ResetButton)
                        .addGap(53, 53, 53)
                        .addComponent(KeluarButton)
                        .addGap(46, 46, 46)
                        .addComponent(SimpanButton))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(112, 112, 112)
                            .addComponent(KarakterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(KalimatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ParagrafLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HasilCariLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(CariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CariButton)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HitungButton)
                    .addComponent(ResetButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(KeluarButton)
                        .addComponent(SimpanButton)))
                .addGap(18, 18, 18)
                .addComponent(kataLabel)
                .addGap(18, 18, 18)
                .addComponent(KarakterLabel)
                .addGap(18, 18, 18)
                .addComponent(KalimatLabel)
                .addGap(18, 18, 18)
                .addComponent(ParagrafLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CariTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HasilCariLabel)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Aplikasi Penghitung Kata");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void KeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KeluarButtonActionPerformed

    private void HitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungButtonActionPerformed
        // TODO add your handling code here:
        hitung();
        
    }//GEN-LAST:event_HitungButtonActionPerformed

    private void SimpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanButtonActionPerformed
        // TODO add your handling code here:
        simpan();
    }//GEN-LAST:event_SimpanButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        // TODO add your handling code here:
        inputTextArea.setText("");
        inputTextArea.requestFocus();
        CariTextField.setText("");
        
        kataLabel.setText("Jumlah Kata : ");
        KarakterLabel.setText("Jumlah Karakter : ");
        KalimatLabel.setText("Jumlah Kalimat : ");
        ParagrafLabel.setText("Jumlah Paragraf : ");
        HasilCariLabel.setText("Hasil Pencarian : ");
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void CariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariButtonActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_CariButtonActionPerformed

    
    
    private void hitung(){
        String input = inputTextArea.getText();
        int jumlahKata = input.isEmpty()?0 : input.split("\\s+").length;
        int jumlahkarakter = input.length();
        int jumlahKalimat = input.isEmpty()?0: input.split("[.!?]").length;
        int jumlahparagraf = input.isEmpty()?0: input.split("\n").length;
        
        kataLabel.setText("Jumlah Kata : "+jumlahKata);
        KarakterLabel.setText("Jumlah Karakter : " +jumlahkarakter);
        KalimatLabel.setText("Jumlah Kalimat : "+jumlahKalimat);
        ParagrafLabel.setText("Jumlah Paragraf : "+jumlahparagraf);
        
    }
    
    private void simpan(){
        String input = inputTextArea.getText();
        try (BufferedWriter output = new BufferedWriter(new FileWriter("hasil_hitung.txt"))) { 
            output.write("Teks :\n"+input+"\n\n");
            output.write(kataLabel.getText()+"\n");
            output.write(KarakterLabel.getText()+"\n");
            output.write(KalimatLabel.getText()+"\n");
            output.write(ParagrafLabel.getText()+"\n");
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke file hasil_hitung.txt");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "gagal menyimpan : ");
        }
    }
    
    private void cari(){
        String input = inputTextArea.getText();
        String cari = CariTextField.getText();
        
        if (cari.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hasil pencarian invalid");
            return;
        }
        
        int indeks=0;
        int kemunculan=0;
        
        Highlighter highlighter = inputTextArea.getHighlighter();
        highlighter.removeAllHighlights();
        
        while ((indeks = input.indexOf(cari,indeks)) != -1) {
            kemunculan++;
            try {
                highlighter.addHighlight(indeks, indeks+cari.length(), new  DefaultHighlighter.DefaultHighlightPainter(java.awt.Color.magenta));
            } catch (BadLocationException ex) {
                ex.printStackTrace();
            }
            indeks +=  cari.length();
        }
        HasilCariLabel.setText("Hasil Pencarian : "+ kemunculan + " kemunculan di temukan");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenghitungKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenghitungKata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CariButton;
    private javax.swing.JTextField CariTextField;
    private javax.swing.JLabel HasilCariLabel;
    private javax.swing.JButton HitungButton;
    private javax.swing.JLabel KalimatLabel;
    private javax.swing.JLabel KarakterLabel;
    private javax.swing.JButton KeluarButton;
    private javax.swing.JLabel ParagrafLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SimpanButton;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kataLabel;
    // End of variables declaration//GEN-END:variables
}
